version: "3.8"

services:
   database:
      container_name: notice-database
      image: mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: password
      volumes:
         - notice-data:/var/lib/mariadb
      networks:
         - dev

volumes:
  notice-data:
   
networks:
   dev: