name: Unit & Static Tests

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    tests:
        runs-on: ubuntu-latest
        env:
            COMPOSE_FILE: .ci/docker-compose.ci.yaml

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Build docker compose file
              run: docker-compose build

            - name: Run docker compose services
              run: docker-compose up -d

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-scripts

            - name: Install node dependencies
              run: npm install

            - name: Build components
              run: npm run build

            - name: Copy test files
              run: cp .env.test .env

            - name: Load migrations
              run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

            - name: Load fixtures
              run: php bin/console doctrine:fixtures:load --env=test --group=TestFixtures --no-interaction

            - name: Run static tests
              run: composer run-script stan-github

            - name: Run unit tests
              run: composer run-script test
